### ISSUE TITLE
ConnectionError: Could not download https://www.whoscored.com/Matches/1815882/Live.

### ISSUE THREAD

**Issue by pranavm28** [probberechts/soccerdata#638] opened 2024-07-10 18:26 UTC
Encountered this while scraping the Jupiler Pro League. One of the matches, which is a Playoff match, has no matchcentre data so whenever the scraper reaches that specific match, it just shuts down and throws the error mentioned in the title. Any fix to this? Any way to avoid the scraper from going to certain games? Awaiting your response. Thanks again for the incredible scraper!

**Comment by probberechts** [comment] 2024-07-10 19:12
Duplicate of #633

**Closed by probberechts** 2024-07-10 19:12 UTC
