### ISSUE TITLE
403 error when downloading FBREF data

### ISSUE THREAD

**Issue by koenklomps** [probberechts/soccerdata#59] opened 2022-07-05 21:17 UTC
Which Python version are you using?

> Python 3.8.13

Which version of soccerdata are you using?

>1.0.1

What did you do?

>fbref = sd.FBref(leagues="NED-Eredivisie", seasons="2021-2022", proxy='tor')
>team_season_stats = fbref.read_schedule()

What did you expect to see?

>Downloaded team stats

What did you see instead?
                          
>requests.exceptions.HTTPError: 403                
>Client Error: Forbidden for url:                  
>https://fbref.com/en/comps/

**Comment by frogman141** [comment] 2022-07-08 17:54
One potential cause of the issue is the new bot scrapping rules for FbRef. They've started to ban anyone scrapping the website at a rate faster than 1 request per 3 seconds. 

If you look into the _common.py code, you can see rate limit and max delay parameters are set to 0 and are currently inaccessible.

**Comment by probberechts** [comment] 2022-07-08 20:26
Indeed, you get a "429 Client Error: Too Many Requests for URL" error if you scrape too fast. Originally the rate limit was set to 1 request per 2 seconds, but it seems they've changed that now to 1 request per 3 seconds. This is actually implemented in `fbref.py` which overrides the default of "no rate limiting" in `_common.py`.

The 403 error is a different issue and I am still convinced that it is caused by the user agent headers. I'll create a pull request in a few minutes and it would be great if you could check whether that solves your issues.

**Comment by frogman141** [comment] 2022-07-09 09:16
Hey, quick update. I trained to change the rate_limit to 3 seconds or more, and unfortunately the same error occurred.

**Comment by probberechts** [comment] 2022-07-09 09:56
> Hey, quick update. I trained to change the rate_limit to 3 seconds or more, and unfortunately the same error occurred.

About which error are you talking now? The 403 or 429 error?

Did you try removing the user agent headers?

**Comment by frogman141** [comment] 2022-07-09 09:59
So the code works now. The quick update above was from me fiddling with the code. I just noticed your hot fix, and It works fine now. Sorry for the confusion.

**Comment by probberechts** [comment] 2022-07-09 10:05
No problem. Thanks for checking!

**Comment by probberechts** [comment] 2022-07-10 14:05
Should  be fixed in v1.0.2 🚀

**Closed by probberechts** 2022-07-10 14:05 UTC
